### ISSUE TITLE
Error while running "npm run build-all"

### ISSUE THREAD

**Issue by rite2bala** [PrivateSky/web-wallet#2]
<img width="1792" alt="Screenshot 2020-09-25 at 11 08 22 AM" src="https://user-images.githubusercontent.com/44022980/94230712-2dc2d100-ff20-11ea-8661-7e803ecc2ba5.png">

hi , I followed the installation guide 
completed the following steps:
npm install 
npm run server 
and when I run npm run build-all i get the error:

```
internal/modules/cjs/loader.js:800
    throw err;
    ^


Error: Cannot find module './../../../privatesky/psknode/bundles/csbBoot.js'
Require stack:
- /Users/ASDF/Desktop/LeafletChat/LeafletAppV1/profile-ssapp-prototype/bin/build.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/ASDF/Desktop/LeafletChat/LeafletAppV1/profile-ssapp-prototype/bin/build.js:8:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/ASDF/Desktop/LeafletChat/LeafletAppV1/profile-ssapp-prototype/bin/build.js'
  ]
}
```
Start copying ./profile-ssapp-prototype/seed to folder ./web-server/secure-channels/apps/profile-ssapp/seed

Could you please guide me where I am going wrong?
I am using the following build:
af307b55f32fbb806dece705fae682752bd9320d

**Comment by Mastaleru** [comment]
the path to build.js file was incorrect. It should be fixed now. Try again by running npm install in your workspace to allow the new changes from psk-profile-ssapp to be pulled into your project.
